dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -e .
  - pip install -r test/requirements.txt
script:
  - pylint --load-plugins pylint_quotes --rcfile=.pylintrc canif/ test/*.py
  - pytest test/